from __future__ import annotations

from dataclasses import dataclass

ASSET_TYPE_FUND = "fund"
ASSET_TYPE_ETF = "etf"


@dataclass(frozen=True)
class ShortResearchAsset:
    asset_type: str
    code: str
    name: str
    category: str
    theme_tags: tuple[str, ...]
    investment_direction: str
    trading_rule_label: str
    tracking_index_code: str | None = None
    exchange: str | None = None


SHORT_TERM_INELIGIBLE_NAME_KEYWORDS = (
    "一年持有",
    "持有期",
    "定开",
    "封闭",
    "封闭期",
    "滚动持有",
)


DEFAULT_SHORT_RESEARCH_ETFS: tuple[ShortResearchAsset, ...] = (
    ShortResearchAsset(ASSET_TYPE_ETF, "510050", "上证50ETF", "broad_index", ("宽基", "大盘"), "上证50大盘蓝筹", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "510300", "沪深300ETF", "broad_index", ("宽基", "核心资产"), "沪深300核心资产", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "510500", "中证500ETF", "broad_index", ("宽基", "中盘"), "中证500中盘成长", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "510880", "红利ETF", "dividend", ("红利", "低波动"), "高股息红利资产", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "510900", "H股ETF", "cross_border", ("港股", "宽基"), "香港H股大盘资产", "T+1跨境ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "511010", "国债ETF", "bond", ("债券", "低波动"), "交易所国债", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "511260", "十年国债ETF", "bond", ("债券", "久期"), "十年期国债", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "511380", "可转债ETF", "bond", ("转债", "弹性"), "可转债资产", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512000", "券商ETF", "sector", ("金融", "证券"), "证券公司板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512010", "医药ETF", "sector", ("医药", "防御"), "医药行业", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512070", "证券保险ETF", "sector", ("金融", "保险"), "证券保险板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512100", "中证1000ETF", "broad_index", ("宽基", "小盘"), "中证1000小盘资产", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512170", "医疗ETF", "sector", ("医疗", "医药"), "医疗服务与器械", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512200", "房地产ETF", "sector", ("地产", "周期"), "房地产板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512400", "有色金属ETF", "sector", ("有色", "周期"), "有色金属板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512480", "半导体ETF", "sector", ("半导体", "芯片", "科技"), "半导体和芯片产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512660", "军工ETF", "sector", ("军工", "高端制造"), "国防军工板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512690", "酒ETF", "sector", ("消费", "白酒"), "白酒消费板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512760", "芯片ETF", "sector", ("芯片", "半导体", "科技"), "芯片产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512800", "银行ETF", "sector", ("金融", "银行"), "银行板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512880", "证券ETF", "sector", ("金融", "证券"), "证券公司板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "512980", "传媒ETF", "sector", ("传媒", "游戏"), "传媒互联网内容", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513030", "德国ETF", "cross_border", ("跨境", "欧洲"), "德国股票市场", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513050", "中概互联网ETF", "cross_border", ("中概", "互联网"), "海外中概互联网", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513060", "恒生医疗ETF", "cross_border", ("港股", "医疗"), "香港医疗健康", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513100", "纳指ETF", "cross_border", ("跨境", "纳斯达克", "科技"), "纳斯达克100", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513130", "恒生科技ETF", "cross_border", ("港股", "科技"), "恒生科技指数", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513180", "恒生科技指数ETF", "cross_border", ("港股", "科技"), "恒生科技指数", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513300", "纳斯达克ETF", "cross_border", ("跨境", "纳斯达克"), "纳斯达克市场", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513500", "标普500ETF", "cross_border", ("跨境", "标普500"), "美国标普500", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513520", "日经ETF", "cross_border", ("跨境", "日本"), "日本股票市场", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "513550", "港股通互联网ETF", "cross_border", ("港股", "互联网"), "港股互联网平台", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515000", "科技ETF", "sector", ("科技", "成长"), "科技龙头板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515030", "新能源车ETF", "sector", ("新能源车", "电力设备"), "新能源汽车产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515050", "5GETF", "sector", ("通信", "5G", "科技"), "5G通信产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515070", "人工智能AIETF", "sector", ("AI", "计算机", "科技"), "人工智能产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515220", "煤炭ETF", "sector", ("煤炭", "周期"), "煤炭能源板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515230", "软件ETF", "sector", ("软件", "计算机"), "软件服务板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515250", "智能汽车ETF", "sector", ("智能汽车", "汽车"), "智能汽车产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515700", "新能车ETF", "sector", ("新能源车", "电力设备"), "新能源汽车板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515790", "光伏ETF", "sector", ("光伏", "电力设备", "新能源"), "光伏产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "515880", "通信ETF", "sector", ("通信", "科技"), "通信设备与运营", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "516010", "游戏ETF", "sector", ("游戏", "传媒"), "游戏传媒板块", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "516160", "新能源ETF", "sector", ("新能源", "电力设备"), "新能源产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "516510", "云计算ETF", "sector", ("云计算", "计算机"), "云计算产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "516970", "基建50ETF", "sector", ("基建", "稳增长"), "基础设施建设", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "517090", "电池ETF", "sector", ("电池", "新能源"), "动力电池产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "518880", "黄金ETF", "commodity", ("黄金", "避险"), "黄金现货相关资产", "T+0可能ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "588000", "科创50ETF", "broad_index", ("科创", "科技"), "科创板50", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "588080", "科创板50ETF", "broad_index", ("科创", "科技"), "科创板50", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "588200", "科创芯片ETF", "sector", ("科创", "芯片"), "科创芯片产业链", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "588220", "科创创业50ETF", "broad_index", ("科创", "创业板"), "科创创业50", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "588300", "双创龙头ETF", "broad_index", ("科创", "创业板"), "双创龙头资产", "T+1股票ETF", exchange="SH"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159605", "中概互联ETF", "cross_border", ("中概", "互联网"), "中概互联网平台", "T+0可能ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159607", "中概互联网ETF", "cross_border", ("中概", "互联网"), "中概互联网平台", "T+0可能ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159611", "电力ETF", "sector", ("电力", "公用事业"), "电力与公用事业", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159632", "纳斯达克ETF", "cross_border", ("跨境", "纳斯达克"), "纳斯达克100", "T+0可能ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159755", "电池ETF", "sector", ("电池", "新能源"), "动力电池产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159766", "旅游ETF", "sector", ("旅游", "消费"), "旅游出行板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159781", "双创50ETF", "broad_index", ("科创", "创业板"), "科创创业50", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159806", "新能源车ETF", "sector", ("新能源车", "电力设备"), "新能源汽车产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159819", "人工智能ETF", "sector", ("AI", "计算机", "科技"), "人工智能产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159825", "农业ETF", "sector", ("农业", "消费"), "农业产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159839", "生物药ETF", "sector", ("医药", "生物药"), "生物医药板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159845", "中证1000ETF", "broad_index", ("宽基", "小盘"), "中证1000小盘资产", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159852", "软件ETF", "sector", ("软件", "计算机"), "软件服务板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159857", "光伏ETF", "sector", ("光伏", "新能源"), "光伏产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159865", "养殖ETF", "sector", ("农业", "养殖"), "畜牧养殖板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159869", "游戏ETF", "sector", ("游戏", "传媒"), "游戏传媒板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159870", "化工ETF", "sector", ("化工", "周期"), "化工板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159871", "有色ETF", "sector", ("有色", "周期"), "有色金属板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159915", "创业板ETF", "broad_index", ("创业板", "成长"), "创业板核心资产", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159919", "沪深300ETF", "broad_index", ("宽基", "核心资产"), "沪深300核心资产", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159922", "中证500ETF", "broad_index", ("宽基", "中盘"), "中证500中盘资产", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159928", "消费ETF", "sector", ("消费", "内需"), "主要消费板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159929", "医药ETF", "sector", ("医药", "防御"), "医药行业", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159934", "黄金ETF", "commodity", ("黄金", "避险"), "黄金现货相关资产", "T+0可能ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159941", "纳指ETF", "cross_border", ("跨境", "纳斯达克"), "纳斯达克100", "T+0可能ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159949", "创业板50ETF", "broad_index", ("创业板", "成长"), "创业板50", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159967", "创成长ETF", "broad_index", ("创业板", "成长"), "创业成长资产", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159995", "芯片ETF", "sector", ("芯片", "半导体", "科技"), "芯片产业链", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159996", "家电ETF", "sector", ("家电", "消费"), "家电消费板块", "T+1股票ETF", exchange="SZ"),
    ShortResearchAsset(ASSET_TYPE_ETF, "159998", "计算机ETF", "sector", ("计算机", "科技"), "计算机软件硬件", "T+1股票ETF", exchange="SZ"),
)


DEFAULT_SHORT_RESEARCH_FUNDS: tuple[ShortResearchAsset, ...] = (
    ShortResearchAsset(ASSET_TYPE_FUND, "110020", "易方达沪深300ETF联接A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000051", "华夏沪深300ETF联接A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "007339", "易方达沪深300ETF联接C", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001052", "华夏中证500ETF联接A", "broad_index", ("宽基", "中证500"), "中证500中盘资产", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "162711", "广发中证500ETF联接A", "broad_index", ("宽基", "中证500"), "中证500中盘资产", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000478", "建信中证500指数增强A", "broad_index", ("宽基", "指数增强"), "中证500指数增强", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "110026", "易方达创业板ETF联接A", "broad_index", ("创业板", "成长"), "创业板核心资产", "场外基金，按净值确认", "CHINEXT"),
    ShortResearchAsset(ASSET_TYPE_FUND, "011608", "易方达上证科创50联接A", "broad_index", ("科创", "科技"), "科创板50", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001051", "华夏上证50ETF联接A", "broad_index", ("宽基", "大盘"), "上证50大盘蓝筹", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "090010", "大成中证红利指数A", "dividend", ("红利", "低波动"), "高股息红利资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161725", "招商中证白酒指数A", "sector", ("消费", "白酒"), "白酒消费板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160222", "国泰国证食品饮料行业A", "sector", ("消费", "食品饮料"), "食品饮料板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000248", "汇添富中证主要消费ETF联接A", "sector", ("消费", "内需"), "主要消费板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001180", "广发医药卫生联接A", "sector", ("医药", "防御"), "医药卫生板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161726", "招商国证生物医药指数A", "sector", ("医药", "生物药"), "生物医药板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001594", "天弘中证银行ETF联接A", "sector", ("金融", "银行"), "银行板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001552", "天弘中证证券保险A", "sector", ("金融", "证券"), "证券保险板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "020021", "国泰金融ETF联接A", "sector", ("金融", "证券"), "金融板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005693", "广发中证军工ETF联接C", "sector", ("军工", "高端制造"), "国防军工板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001618", "天弘中证电子ETF联接C", "sector", ("电子", "科技"), "电子产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001629", "天弘中证计算机ETF联接A", "sector", ("计算机", "科技"), "计算机软件硬件", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "004752", "广发中证传媒ETF联接A", "sector", ("传媒", "游戏"), "传媒互联网内容", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "110007", "易方达稳健收益债券A", "bond", ("债券", "低波动"), "稳健债券资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "003547", "鹏华丰禄债券", "bond", ("债券", "低波动"), "债券资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "070009", "嘉实超短债债券C", "bond", ("债券", "短债"), "短债资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000217", "华安黄金ETF联接C", "commodity", ("黄金", "避险"), "黄金资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "270042", "广发纳斯达克100ETF联接A", "qdii", ("跨境", "纳斯达克"), "纳斯达克100", "场外QDII，净值和确认可能延迟", "NDX100"),
    ShortResearchAsset(ASSET_TYPE_FUND, "050025", "博时标普500ETF联接A", "qdii", ("跨境", "标普500"), "美国标普500", "场外QDII，净值和确认可能延迟", "SP500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000071", "华夏恒生ETF联接A", "qdii", ("港股", "宽基"), "香港恒生指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "006327", "易方达中证海外互联ETF联接A", "qdii", ("中概", "互联网"), "海外中概互联网", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161130", "易方达纳斯达克100指数A", "qdii", ("跨境", "纳斯达克"), "纳斯达克100", "场外QDII，净值和确认可能延迟", "NDX100"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000948", "华夏沪港通恒生ETF联接A", "qdii", ("港股", "宽基"), "香港恒生指数", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "008086", "华夏中证5G通信主题ETF联接A", "sector", ("通信", "5G"), "5G通信产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "008887", "华夏国证半导体芯片ETF联接A", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005827", "易方达蓝筹精选混合", "active", ("消费", "港股"), "主动权益蓝筹资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005911", "广发双擎升级混合A", "active", ("科技", "成长"), "主动成长权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "004997", "广发高端制造股票A", "active", ("高端制造", "新能源"), "高端制造产业", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "004856", "广发中证全指建筑材料A", "sector", ("建材", "周期"), "建筑材料板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161017", "富国中证500指数增强A", "broad_index", ("宽基", "指数增强"), "中证500指数增强", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161028", "富国中证新能源汽车指数A", "sector", ("新能源车", "电力设备"), "新能源汽车产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161024", "富国中证军工指数A", "sector", ("军工", "高端制造"), "国防军工板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161005", "富国天惠成长混合A", "active", ("成长", "主动权益"), "主动成长权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "100032", "富国中证红利指数增强A", "dividend", ("红利", "低波动"), "高股息红利资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "100038", "富国沪深300增强A", "broad_index", ("宽基", "指数增强"), "沪深300指数增强", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161032", "富国中证煤炭指数A", "sector", ("煤炭", "周期"), "煤炭能源板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160632", "鹏华酒指数A", "sector", ("消费", "白酒"), "白酒消费板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160633", "鹏华证券保险A", "sector", ("金融", "证券"), "证券保险板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160629", "鹏华传媒指数A", "sector", ("传媒", "游戏"), "传媒互联网内容", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160638", "鹏华一带一路A", "sector", ("基建", "周期"), "一带一路与基建", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160616", "鹏华中证500指数A", "broad_index", ("宽基", "中证500"), "中证500中盘资产", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005802", "汇添富智能制造股票A", "active", ("高端制造", "智能制造"), "智能制造产业", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000083", "汇添富消费行业混合", "active", ("消费", "主动权益"), "消费行业主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "470028", "汇添富社会责任混合A", "active", ("成长", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "202015", "南方沪深300ETF联接A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "202021", "南方小康产业联接A", "sector", ("宽基", "消费"), "小康产业指数", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160119", "南方中证500ETF联接A", "broad_index", ("宽基", "中证500"), "中证500中盘资产", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "160142", "南方标普中国A股大盘红利A", "dividend", ("红利", "大盘"), "大盘红利资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000176", "嘉实沪深300ETF联接A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000008", "嘉实中证500ETF联接A", "broad_index", ("宽基", "中证500"), "中证500中盘资产", "场外基金，按净值确认", "CSI500"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000082", "嘉实研究阿尔法股票A", "active", ("成长", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "050002", "博时沪深300指数A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "050026", "博时医疗保健行业A", "sector", ("医药", "医疗"), "医疗保健行业", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "050201", "博时价值增长混合", "active", ("价值", "主动权益"), "主动价值权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "040046", "华安纳斯达克100A", "qdii", ("跨境", "纳斯达克"), "纳斯达克100", "场外QDII，净值和确认可能延迟", "NDX100"),
    ShortResearchAsset(ASSET_TYPE_FUND, "040008", "华安策略优选混合A", "active", ("价值", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "040002", "华安中国A股增强指数", "broad_index", ("宽基", "指数增强"), "A股增强指数", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "090018", "大成新锐产业混合A", "active", ("成长", "制造"), "新锐产业主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161831", "银华恒生国企指数A", "qdii", ("港股", "国企"), "香港国企指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161834", "银华鑫锐灵活配置A", "active", ("成长", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "161812", "银华深证100指数A", "broad_index", ("宽基", "深证100"), "深证100指数", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "163402", "兴全趋势投资混合", "active", ("价值", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "163406", "兴全合润混合", "active", ("成长", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "260108", "景顺长城新兴成长混合A", "active", ("成长", "消费"), "主动成长权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "260109", "景顺长城内需增长混合", "active", ("消费", "内需"), "内需消费主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "166002", "中欧新蓝筹混合A", "active", ("价值", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "166011", "中欧盛世成长混合A", "active", ("成长", "主动权益"), "主动成长权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "519736", "交银新成长混合", "active", ("成长", "主动权益"), "主动成长权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "519069", "汇添富价值精选混合A", "active", ("价值", "主动权益"), "主动价值权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "481012", "工银深证红利ETF联接A", "dividend", ("红利", "深证"), "深证红利资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000831", "工银医疗保健股票A", "sector", ("医药", "医疗"), "医疗保健行业", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "530018", "建信深证基本面60ETF联接A", "broad_index", ("宽基", "价值"), "深证基本面60", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "660008", "农银沪深300指数A", "broad_index", ("宽基", "沪深300"), "沪深300核心资产", "场外基金，按净值确认", "CSI300"),
    ShortResearchAsset(ASSET_TYPE_FUND, "519183", "万家双引擎灵活配置", "active", ("成长", "主动权益"), "主动权益资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "320007", "诺安成长混合", "active", ("半导体", "科技"), "半导体科技主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "519674", "银河创新成长混合A", "active", ("科技", "成长"), "科技成长主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000536", "前海开源可转债债券", "bond", ("转债", "弹性"), "可转债资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "000216", "华安黄金ETF联接A", "commodity", ("黄金", "避险"), "黄金资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "006479", "广发纳斯达克100ETF联接C", "qdii", ("跨境", "纳斯达克"), "纳斯达克100", "场外QDII，净值和确认可能延迟", "NDX100"),
    ShortResearchAsset(ASSET_TYPE_FUND, "040047", "华安纳斯达克100C", "qdii", ("跨境", "纳斯达克"), "纳斯达克100", "场外QDII，净值和确认可能延迟", "NDX100"),
    ShortResearchAsset(ASSET_TYPE_FUND, "008888", "华夏国证半导体芯片ETF联接C", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "007300", "国联安中证全指半导体ETF联接A", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "007301", "国联安中证全指半导体ETF联接C", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012629", "广发国证半导体芯片ETF联接A", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012630", "广发国证半导体芯片ETF联接C", "sector", ("半导体", "芯片"), "半导体和芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "014776", "富国中证芯片产业ETF联接A", "sector", ("芯片", "科技"), "芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "014777", "富国中证芯片产业ETF联接C", "sector", ("芯片", "科技"), "芯片产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "011103", "天弘中证光伏产业A", "sector", ("光伏", "新能源"), "光伏产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "011102", "天弘中证光伏产业C", "sector", ("光伏", "新能源"), "光伏产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001410", "信澳新能源产业股票", "active", ("新能源", "电力设备"), "新能源产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "002190", "农银新能源主题", "active", ("新能源", "电力设备"), "新能源主题主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001156", "申万菱信新能源汽车", "sector", ("新能源车", "汽车"), "新能源汽车产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "004854", "广发中证全指汽车A", "sector", ("汽车", "新能源车"), "汽车产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005669", "前海开源公用事业股票", "active", ("电力", "公用事业"), "公用事业与电力资产", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001475", "易方达国防军工混合A", "active", ("军工", "高端制造"), "军工主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "006736", "国投瑞银先进制造混合", "active", ("高端制造", "新能源"), "先进制造主动权益", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001630", "天弘中证计算机ETF联接C", "sector", ("计算机", "科技"), "计算机软件硬件", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001619", "天弘中证电子ETF联接A", "sector", ("电子", "科技"), "电子产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012414", "招商中证白酒指数C", "sector", ("消费", "白酒"), "白酒消费板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012043", "鹏华酒指数C", "sector", ("消费", "白酒"), "白酒消费板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "015679", "华夏中证机器人ETF联接A", "sector", ("机器人", "高端制造"), "机器人产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "015680", "华夏中证机器人ETF联接C", "sector", ("机器人", "高端制造"), "机器人产业链", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "013171", "华夏恒生科技ETF联接A", "qdii", ("港股", "科技"), "恒生科技指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "013172", "华夏恒生科技ETF联接C", "qdii", ("港股", "科技"), "恒生科技指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012348", "天弘恒生科技指数A", "qdii", ("港股", "科技"), "恒生科技指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "012349", "天弘恒生科技指数C", "qdii", ("港股", "科技"), "恒生科技指数", "场外QDII，净值和确认可能延迟"),
    ShortResearchAsset(ASSET_TYPE_FUND, "001632", "天弘中证食品饮料ETF联接C", "sector", ("消费", "食品饮料"), "食品饮料板块", "场外基金，按净值确认"),
    ShortResearchAsset(ASSET_TYPE_FUND, "005223", "广发中证基建工程ETF联接A", "sector", ("基建", "稳增长"), "基础设施建设", "场外基金，按净值确认"),
)


DEFAULT_SHORT_RESEARCH_ASSETS = DEFAULT_SHORT_RESEARCH_ETFS + DEFAULT_SHORT_RESEARCH_FUNDS
DEFAULT_SHORT_RESEARCH_ETF_CODES = tuple(asset.code for asset in DEFAULT_SHORT_RESEARCH_ETFS)
DEFAULT_SHORT_RESEARCH_FUND_CODES = tuple(asset.code for asset in DEFAULT_SHORT_RESEARCH_FUNDS)
SHORT_RESEARCH_ASSET_BY_KEY = {
    (asset.asset_type, asset.code): asset for asset in DEFAULT_SHORT_RESEARCH_ASSETS
}


def is_short_term_eligible_name(name: str) -> bool:
    return not any(keyword in name for keyword in SHORT_TERM_INELIGIBLE_NAME_KEYWORDS)
